# Generated by Django 6.1 on 2026-09-01 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLineDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('title', models.CharField(default='프로젝트 01', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schema_data', models.JSONField(default=dict, help_text='JointJS graph cells and SLD metadata')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '전력 계통도',
                'verbose_name_plural': '전력 계통도 목록',
                'ordering': ['-updated_at'],
            },
        ),
    ]
